### ISSUE TITLE
convert stml to gdml (material missing?)

### ISSUE THREAD

**Issue by Pas-dn** [tihonav/cad-to-geant4-converter#3]
Following your instruction I‘m trying to convert a stml to gdml file.
I use the following command:

python stl_gdml.py target0 target.stl

Then I get the following message:
python stl_gdml.py target0 target.stl
Processing file     target.stl:  100.0%()
Could not parse material for the file target.stl: - asigning Vacuum to this volume!

I guess there is a problem in loading the material, isn’t it?

If I try to visualize the .gdml file by root
I get the error

root [0] TGeoManager::Import("target0.gdml");
Info in <TGeoManager::Import>: Reading geometry from file: target0.gdml
Info in <TGeoManager::TGeoManager>: Geometry GDMLImport, Geometry imported from GDML created
Error: Function StartGDML("target0.gdml") is not defined in current scope  (tmpfile):1:
*** Interpreter error recovered ***
Error in <TGeoManager::Import>: Cannot open file

or by

source /afs/cern.ch/work/a/andrii/public/GDML/setup_geant4_gdml_xerces.sh
cp /afs/cern.ch/work/a/andrii/public/GDML/Example/vis.mac ./
load_gdml target0.gdml 

I don’t see anything and the following messages

G4GDML: Reading 'target0.gdml'...
G4GDML: VALIDATION ERROR! element 'materials' is not allowed for content model '((define,materials,solids,structure,userinfo),setup)' at line: 288
G4GDML: Reading materials...
G4GDML: Reading solids...
G4GDML: Reading structure...
G4GDML: Reading module 'target.gdml'...
G4GDML: VALIDATION ERROR! empty content is not valid for content model '(Facet,)' at line: 9
G4GDML: VALIDATION ERROR! element 'solids' is not allowed for content model '((define,materials,solids,structure,userinfo),setup)' at line: 22
G4GDML: VALIDATION ERROR! ID attribute 'Vacuum' is referenced but was never declared at line: 22
G4GDML: Reading definitions...
G4GDML: Reading solids...
G4GDML: Reading structure...
G4GDML: Reading setup...
G4GDML: Reading module 'target.gdml' done!
G4GDML: Reading setup...
G4GDML: Reading 'target0.gdml' done!
Stripping off GDML names of materials, solids and volumes ...

*************************************************************
 Geant4 version Name: geant4-09-06-patch-03    (14-March-2014)
                      Copyright : Geant4 Collaboration
                      Reference : NIM A 506 (2003), 250-303
                            WWW : http://cern.ch/geant4
*************************************************************

Available UI session types: [ Qt, Xm, GAG, tcsh, csh ]
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**Comment by tihonav** [comment]
1) For the material, you should mention it in the file name, for example, see:
https://github.com/tihonav/cad-to-geant4-converter/tree/master/Example

In other words, simply rename your .stl file according to the type of material, to which it corresponds, e.g.   target0  --> target0_Gold   (if it's made of gold)

For more info about materials, see:
https://github.com/tihonav/cad-to-geant4-converter/blob/master/README.md#materials

2) For the root  GDML visualisation, it seems that your ROOT doesn't have the GDML module enabled, see.

The issue is covered on the ROOT forum:
https://root-forum.cern.ch/t/problem-using-tgeomanager-import-with-gdml-file/4366

3) For the Geant4 visualisation, please attach your target0.stl to trace the problem.

**Comment by Pas-dn** [comment]
Ok, great, renaming the file as target_Aluminum.stl worked perfectly.

Now the visualisation. The file is 
/afs/cern.ch/user/p/pdinezza/public/xgdml/mytarget.gdml

typing
source /afs/cern.ch/work/a/andrii/public/GDML/setup_geant4_gdml_xerces.sh
cp /afs/cern.ch/work/a/andrii/public/GDML/Example/vis.mac ./
load_gdml mytarget.gdml 

I get:
source /afs/cern.ch/work/a/andrii/public/GDML/setup_geant4_gdml_xerces.sh
Setting python2.7..
Setting GCC..
Setting geant4..
Setting xerces
~ $ load_gdml mytarget.gdml 
load_gdml: /afs/cern.ch/sw/lcg/contrib/gcc/4.8.1/x86_64-slc6-gcc48-opt/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_88/qt/4.8.7/x86_64-slc6-gcc49-opt/lib/libQtCore.so.4)
load_gdml: /afs/cern.ch/sw/lcg/contrib/gcc/4.8.1/x86_64-slc6-gcc48-opt/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_88/qt/4.8.7/x86_64-slc6-gcc49-opt/lib/libQtGui.so.4)
load_gdml: /afs/cern.ch/sw/lcg/contrib/gcc/4.8.1/x86_64-slc6-gcc48-opt/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_88/qt/4.8.7/x86_64-slc6-gcc49-opt/lib/libQtOpenGL.so.4)

For root I'm using this
/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_88/ROOT/6.08.06/x86_64-slc6-gcc49-opt/bin/root
even if strange I understood I'm to install a private version compiling with the gdml configuration 
switched on. Isn't it?

Thanks a lot

**Comment by tihonav** [comment]
Your souce .stl file ( /afs/cern.ch/user/p/pdinezza/public/xgdml/target_Aluminum.stl) is a BINARY STL.  In order to use the converter, you should use ASCII STL instead, see:
https://github.com/tihonav/cad-to-geant4-converter#input

Please check with the CAD tool that you used to produce the stl file, there should be an option of exporting the CAD model to the ASCII STL.

**Comment by kwashabawa** [comment]
Hello, 
I have an Ascii STL file which I have converted to .gdml using similar method as above.
When I tried to make it I get this error as shown in the attachment  
![screenshot from 2018-11-29 17-26-13](https://user-images.githubusercontent.com/45008103/49240062-3c133500-f3fc-11e8-9ed2-65bf9c2cf63b.png)

Can someone please help me out

Thank you
Aliyu

**Comment by kwashabawa** [comment]
Hi Andrii,

The files are too large to be attached here. I have sent a link below which
will give you access to the files that produce the error.
Note: I am using the G04 example to build this.

 neutron-Copper.STL.gdml
<https://drive.google.com/a/udusok.edu.ng/file/d/1KWPHh2CodzE7xBKcMF_VGhfkJ1XnhNLy/view?usp=drive_web>


Thank you
Aliyu

**Comment by tihonav** [comment]
Hi Aliyu,

I can get the  "neutron-Copper.STL.gdml" but I don't have access to the second link, which holds the "newdet.gdml".

Quick question:
 - do you have both GDML files in the same directory when you load them with G04 example program?

Best,
Andrii

**Comment by FelixLdwg** [comment]
Hi,
I got some errors, when i use your tool to convert my .stl to .gdml and run them with Geant4:
'G4GDML: VALIDATION ERROR! element 'materials' is not allowed for content model '(define,materials,solids,structure,userinfo?,setup+)' at line: 416
G4GDML: VALIDATION ERROR! element 'solids' is not allowed for content model '(define,materials,solids,structure,userinfo?,setup+)' at line: 32
G4GDML: VALIDATION ERROR! ID attribute 'Vacuum' is referenced but was never declared at line: 32

This happens as well for every other material, that is defined. [test.zip](https://github.com/tihonav/cad-to-geant4-converter/files/2772649/test.zip) is my cropped .stl file and the converted .gdml files. However I also tried to use the example .stl DAM_EQM_CornerPlastic.stl, which gives me the same error messages with "Aluminum" instead of "Vacuum". Everything looks fine in the Geant4 GUI, but I'm not sure if the materials get parsed correctly cause of the errors.

I load the .gdml with the G01 example of Geant4.

Thanks for your help

**Comment by tihonav** [comment]
Hi,

This is a known feature of GDML parser in G4. You can safely ignore it. The G4 GDML validator complains because the materials are referenced but not defined in the daughter gdml files. At the same time, the materials are defined in the main (parent) gdml file. For example, you can try to change the name of "Aluminum" or "Vacuum" in your main GDML, and you will see that Geant4 will crash because it can't find the material. 

In any case, this doesn't affect the simulation, so you can ignore the "VALIDATION ERROR"s. If you'd like to get rid of them, try putting the corresponding materials in the daughter GDML files. 

Best,
Andrii
